version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:456668253361:task-definition/paidy-task-def:1"
        LoadBalancerInfo:
          ContainerName: "paidy-container"
          ContainerPort: 5000